# Generated by Django 4.0.3 on 2023-01-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_sales_person_salesrecord_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialcustomer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='potentialcustomer',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
