# Generated by Django 4.0.3 on 2023-01-24 18:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobileVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17, 'MUST BE 17 CHARACTERS')])),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=200)),
                ('employee_number', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17, 'MUST BE 17 CHARACTERS')])),
                ('customer_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('reason_for_service', models.TextField()),
                ('vip', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('assigned_technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='service_rest.servicetechnician')),
            ],
        ),
    ]
